### PR TITLE
Do not mask the original error

### PR DESCRIPTION
**Pull request by martinpaljak**
Or debugging becomes harder/impossible.

### CODE REVIEW

**Comment by YuryStrozhevsky** [comment]
Great, but please re-design it to be ES6 code:
```javascript
if(checkBufferParams(const n = new LocalBaseBlock(), inputBuffer, inputOffset, inputLength) === false)
```
Then I will approve and merge it.

**Comment by rmhrisk** [comment]
@martinpaljak will you be able to make this change?

**Comment by martinpaljak** [comment]
I will get to Js related topics in a week or two, busy with backlog at this point of time.

**Comment by YuryStrozhevsky** [comment]
@martinpaljak I have implemented your changes in main code manually. Thanks for the participating!

**Pull request closed without merging**
