### PR TITLE
bug fixes for default case in the LocalFromBER function

### PR DESCRIPTION
**Pull request by TomHirst1984**

### CODE REVIEW

**Comment by YuryStrozhevsky** [comment]
Please explain details and provide test data here.

**Comment by TomHirst1984** [comment]
So the problem can be observed when trying to decode a buffer such as

'60806b80a0806980a0050d03010202a1803180a20c090a8100050fb33333333333000000000000000000000000'

In this, we have a set, which has been encoded using the indefinite form length encoding, and contains a primitive element of type REAL (tag 9). 

Because the REAL type is not handled fully by the library, it is just created as a Primitive object in the default case block (line 5549 of asn1.js), and it is then parsed from the buffer shortly after using returnObject.fromBER - which updates the offset into the buffer. returnObject.fromBER is then called again on line 5585, which causes the object to be read twice from the buffer, causing the zero buffer length issue.

The problem effectively boils down to returnObject.fromBER being called twice when we pass through the default case, but only once in all other cases.

The error handling that this bug triggers also has an issue, where it is assigning the error message to this.error rather than returnObject.error.

**Comment by TomHirst1984** [comment]
Did you ever get a chance to look at this?

**Comment by YuryStrozhevsky** [comment]
@TomHirst1984 Sorry, I will check it as soon as I can.

**Comment by YuryStrozhevsky** [comment]
@TomHirst1984 I have tested all these changes, all works perfectly, thank you.

**Pull request merged**
