### PR TITLE
Add support for relative object identifier type

### PR DESCRIPTION
**Pull request by TomHirst1984**
Add support for the Relative Object Identifier type, which is similar to the object identifier, but without the range limit and compression on the first 2 elements.

### CODE REVIEW

**Comment by YuryStrozhevsky** [comment]
@TomHirst1984 In order to have the code checked please provide correctly encoded Relative Object Identifier (in BASE-64 or hex encoding).

**Comment by TomHirst1984** [comment]
So taking the example from https://www.itu.int/ITU-T/studygroups/com17/languages/X.690-0207.pdf

The relative object id 8571.3.2 should encode as

0D04C27B0302

**Comment by YuryStrozhevsky** [comment]
@TomHirst1984 Had a very busy week, will inspect code soon.

**Comment by TomHirst1984** [comment]
@YuryStrozhevsky Did you ever get a chance to review this?

**Comment by YuryStrozhevsky** [comment]
@TomHirst1984 Sorry, lost the PR among other stuff to do. Will review on Monday.

**Pull request merged**
